# Generated by Django 6.0.6 on 2026-07-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_bids_bid_rename_categories_categorie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
